temperature_summary: 0.6
temperature_diarize: 0.6
top_p_summary: 0.9
top_p_diarize: 0.9
max_new_tokens_summary: 256
max_new_tokens_diarize: 4096
do_sample_summary: True
do_sample_diarize: True
mod_name_summary: 'claude-sonnet' # choose from llama-8b, llama-70b, claude-opus, or claude-sonnet
mod_name_diarize: 'claude-sonnet' # same as above
chunk_num: 3
summary: True
summary_chunking: True # summarize whole transcript for each chunk or summarize corresponding chunk only (if True)
return_chunked: False # if True label each chunk in final transcript (chunk 0, chunk 1...)
claude_key: '/work/bioinformatics/s229618/api_keys/claude_key.txt' # path to personal key in .txt file, required for claude models
