levenshtein: True # if True run evaluations using normalized levenshtein distance
diff: False # if True run evaluations using diff ratio
transcript_preservation: True # if true, return transcript preservation scores
transcript_accuracy_basic: False # if true, return basic transcript accuracy score between diarized and gold standard
transcript_accuracy_baseline_normed: False # if true, return baseline normed transcript accuracy score between diarized and gold standard
transcript_accuracy_opposite_normed: False # if true, return opposite normed transcript accuracy score between diarized and gold standard
chunk_num: 1 # if higher than 1, calculate accuracy for each chunk of transcript